### ISSUE TITLE
Peakzilla ChIP-exo published result data (Rhee and Pugh, 2011) replication

### ISSUE THREAD

**Issue by sudhirjadhao** [steinmann/peakzilla#6]
Dear Jonas ,

Greetings for the day !!!

I have chip-exo data.  To call peak, I am planning to used peakzilla. 
Before trying out on our lab data, my boss wants me to replicate the result published in peakzilla paper.

I have three bam file for three replicates of CTCF data from Rhee and Pugh,2011. I run Peakzilla with default parameter,

Below are the results I got
![image](https://user-images.githubusercontent.com/10668260/29761040-c20ecbfe-8bf9-11e7-94c1-99ae5ff10ac3.png)

But in publication, you have mentioned  36 bp peak and 60 smallest peak to peak distance.

I think it may be the peakzilla version which I am using is different than used during publication.

Can you please explain to me why I am getting such results.

Command used:

python ~/Tools/peakzilla-master/peakzilla.py input.bed >$out"s1_peaks.tsv"

Best Regards,
Sudhir

**Comment by abardet** [comment]
Dear Sudhir,

Thanks for your interest in using peakzilla to analyse your ChIP-exo data.

At the time of publication, the CTCF ChIP-exo data was not available online so we had obtained mapped reads from the authors directly (Rhee and Pugh 2011). We also cut the reads to 36bp to be consistent with read length of other samples used for benchmarking peakzilla. So already, the bam files you used might be slightly different than our inputs.

About the peak sizes, we report for CTCF a fragment size of 36bp and so the peak size being twice the estimated fragment size would be 72bp so very close to the 70bp you just got. For the smallest peak-to-peak distance, we did not use the minimum of all possible peak-to-peak distances since it could be an outlier but the 1% quantile to be more robust, which led to 60bp for CTCF. Only minor updates were added to peakzilla since the publication so this should not change the results.

I hope this helps and let me know if you have more questions.
Anaïs

**Comment by sudhirjadhao** [comment]
Dear Jonas ,

Greetings for the day !!!

Thank you for the reply and valuable inputs.

All the points made by you make sense.

Can you please tell me how you have processed replicate data? means did you merged bam files or called peak on each replicate then merge data?

Best Regards,
Sudhir

**Comment by abardet** [comment]
Dear Sudhir,

We always process replicated samples separately so it can be useful to assess reproducibility. We used replicate 1 for the plot in the paper. We have actually discussed this strategy in this paper: A computational pipeline for comparative ChIP-seq analyses (doi:10.1038/nprot.2011.420)

Best regards,
Anaïs

**Comment by sudhirjadhao** [comment]
Thank you for your valuable time and inputs.

I will go through the paper.

Best Regards,
Sudhir
